### ISSUE TITLE
Unmatched left/right join no longer returns null field?

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#101]
Sorry I am a bit of hurry so not yet have time to investigate further. Just to jot down my guess here. In the past a join, e.g.: `db.foo.leftJoin(db.bar)` will return `row.bar == null` if there is no match. But I think now it seems to be `row.bar == {field1: null, field2: null}`.

If that is the case it is a breaking change...

**Comment by benmerckx** [comment]
It's an oversight. Or rather it was unspecified before? We left most of the nesting to the driver before. The change comes from selecting every field and then reassembling the nested response. It can be reintroduced.

**Comment by kevinresol** [comment]
I think that have to reintroduce it, it broke my server silently

**Comment by benmerckx** [comment]
It was defined in the mysql driver here:

https://github.com/haxetink/tink_sql/blob/f99e86b597996011b718606d923436556a3157e2/src/tink/sql/drivers/node/MySql.hx#L175-L185

Should be consistent across drivers now
