### ISSUE TITLE
[sqlite]support ":memory:" database 

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_sql#103]
current sqlite version do not support ":memory:"  database.

please consider to support !

[test](https://gist.github.com/sonygod/7284d1675847937207c5c15db729d766)

**Comment by benmerckx** [comment]
The test suite runs fine on a :memory: database: https://github.com/haxetink/tink_sql/commit/5e1567d62000cb00d3a240d16c7df67b6472da3f
Could you reduce the example or be more specific what fails?

**Comment by sonygod** [comment]
import tink.sql.Database;

		using tink.CoreApi;

		import tink.sql.Types;

		typedef Customer = {
			@:autoIncrement @:primary public var id(default, null):Id<Customer>;
			public var avatar(default, null):VarChar<50>;
		}

		class Db extends tink.sql.Database {
			@:table var fa_customer:Customer;

			public var user(get, never):tink.sql.Table<{fa_customer:Customer}>;

			inline function get_user()
				return fa_customer;
		}

		@await
		class Main {
			static var db:Db;

			@async
			static function main() {
				var driver2 = new tink.sql.drivers.Sqlite(function(db) {
					return ":memory:";
				});
				db = new Db('fa_klw', driver2);

				db.user.create();
				trace('create table'); // work.
				var one = @await testInsert(); // not work.
				var two = @await testInsert();
				trace(one); 
				trace(two); 
				trace("finish");
			}

			static function testInsert() {
				return db.user.insertOne({
					id: cast null,
					avatar: "TEST.PNG",
				});
			}
		}

**Comment by sonygod** [comment]
not work with tink_await together.

**Comment by kevinresol** [comment]
Test running fine. Closing.
