### ISSUE TITLE
sqlite insert error.

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_sql#104]
import tink.sql.Database;

	using tink.CoreApi;

	import tink.sql.Types;

	typedef Customer = {
		@:autoIncrement @:primary public var id(default, null):Id<Customer>;
		public var avatar(default, null):VarChar<50>;
	}

	class Db extends tink.sql.Database {
		@:table var fa_customer:Customer;

		public var user(get, never):tink.sql.Table<{fa_customer:Customer}>;

		inline function get_user()
			return fa_customer;
	}

	@await
	class Main {
		static var db:Db;

		@async
		static function main() {
			var driver2 = new tink.sql.drivers.Sqlite(function(db) {
				return "db.db";
			});
			db = new Db('fa_klw', driver2);

			db.user.create();
			trace('create table'); // work.
			var one = @await testInsert(); // not work.

			trace(one.rowsAffected); // no trace.

			trace("finish");
		}

		static function testInsert() {
			return db.user.insertOne({
				id: cast null,
				avatar: "TEST.PNG",
			});
		}
	}

**Comment by kevinresol** [comment]
It would be nice if you can remove the tink_await dependency so we have one less factor to worry about.

**Comment by sonygod** [comment]
after remove all tink_await.
this line not work 

   trace(one.rowsAffected); // no trace

**Comment by back2dos** [comment]
Hmm, my guess is that table creation is async and synchronously inserting into a table that was just created somehow fails?

**Comment by benmerckx** [comment]
A few things are going on here:
- create is async and must be awaited
- insertOne did not have a defined return type: I've typed it explicitly in 8279c24 since it returns a `Promise<Id<Db>>`, not `Promise<{rowsAffected: Int}>`

Other than that there's no actual issue here.
