### ISSUE TITLE
Replace the geojson library

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#110]
a few cons of geojson

1. typing is very messy because it carries a runtime "type" string
2. the object wrapper causes unnecessary overhead
3. mutable

I created another lib for geometries. Data are just abstracts over `Array<Float>` and uses enum to distinguish them.

https://github.com/why-haxe/why-geometry/tree/master/src/why/g2d

@back2dos if you wish, I can move that to haxetink

**Comment by back2dos** [comment]
You're free of course to move it to haxetink. There might be a bit of confusion about how it relates to tink_geom2. Perhaps it would then be best to call it tink_geojson - if dealing with geojson is indeed its primary objective (which at least right now seems to be the case).

**Comment by kevinresol** [comment]
The primary goal is to actually ditch geojson (the json form is the source of all the problems)

Any other name suggestions?

**Comment by benmerckx** [comment]
tink_spatial?
