### ISSUE TITLE
Comparison is reversed for "less than (a date)"

### ISSUE THREAD

**Issue by cedx** [haxetink/tink_sql#133]
This query (using the MySQL/PDO driver with PHP 8):

```haxe
myDb.myTable.where(myTable.createdAt < Date.now()).all();
```

...generates this SQL code:

```sql
SELECT *
FROM `native_table` AS `myTable`
WHERE ('2021-06-22 18:40:13' > `myTable`.`createdAt`)
```

As you can see, the comparison is reversed (i.e. "date > field" instead of "field < date").
Under normal circumstances (i.e. querying a MySQL/MariaDB server), this is not an issue. But we have a very special setup at my work...

Our main database server is MS SQL Server 2000 :sob: In order to be able to query it from `tink_sql` (and everything else: SQL Server 2000 is too old for most apps/libraries nowadays), we use the [MariaDB CONNECT engine](https://mariadb.com/kb/en/introduction-to-the-connect-engine) (i.e. SQL Server is queried through MariaDB and a proper ODBC driver).

This is where things get interesting: when the comparison is reversed (`'2021-06-22 18:40:13' > createdAt`), the query fails. But when the comparison order is respected (`createdAt < '2021-06-22 18:40:13'`), the query succeeds. The mysteries of SQL Server and ODBC.

I don't really know if anything can be done on the `tink_sql` side... but I didn't expect to see this kind of inversion in the SQL query produced (i.e. most of the time, SQL statements respect the original Haxe code).

Haxe 4.2.2 on Windows 10, `tink_sql` 72d61bd9947a9614487388bc152fa6ece05bc294 (i.e. the last commit at the time of writing).

**Comment by benmerckx** [comment]
There's two more reasons to produce queries closer to the dsl:
- Easier to debug resulting queries
- Some sql servers require subqueries to be on the right hand side of an expression

**Comment by cedx** [comment]
Thanks @benmerckx !
