### ISSUE TITLE
how to write something like is not null or is null in sql?

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_sql#136]
`  var result=@await db.F_NODE.select({phone:F_NODE.phone}).where(F_NODE.totalReceived>0&&F_NODE.phone!=null).all();`

`F_NODE.phone!=null` is not work

how to fixed that?

**Comment by benmerckx** [comment]
https://github.com/haxetink/tink_sql/blob/cc9d2bd78d373ab32aba56ff97c586f0d29cb58a/src/tink/sql/Expr.hx#L236-L237

````
!F_NODE.phone.isNull()
````
