### ISSUE TITLE
date compare  expr wrong!

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_sql#138]
I have some test  here

```haxe
	var rs3 = @await db.F_NODE.select({totalReceived: F_NODE.totalReceived,updateTime:F_NODE.updateTime}).where(F_NODE.updateTime >= new Date(2021,7,1,0,0,0) && F_NODE.totalReceived > 1).all();
```

//got nothing ,return [] ;empty array.

when I change condition from `  new Date(2021,7,1,0,0,0) to  new Date(2021,6,1,0,0,0)`

I got 

` { totalReceived: 2, updateTime: 2021-06-27T07:39:15.000Z },
  { totalReceived: 2, updateTime: 2021-06-27T07:39:08.000Z },
  { totalReceived: 2, updateTime: 2021-06-27T07:39:13.000Z },
  { totalReceived: 3, updateTime: 2021-06-27T07:39:11.000Z },
  { totalReceived: 3, updateTime: 2021-06-27T07:39:14.000Z },
  { totalReceived: 3, updateTime: 2021-06-27T07:39:11.000Z },
  { totalReceived: 2, updateTime: 2021-07-13T01:48:19.000Z },
  { totalReceived: 2, updateTime: 2021-07-14T02:33:35.000Z },
  { totalReceived: 2, updateTime: 2021-07-13T01:48:18.000Z },
  { totalReceived: 2, updateTime: 2021-07-05T21:29:43.000Z },
  { totalReceived: 3, updateTime: 2021-07-05T22:14:48.000Z },
  { totalReceived: 3, updateTime: 2021-07-05T22:20:53.000Z },
  { totalReceived: 3, updateTime: 2021-07-05T23:03:21.000Z },
  { totalReceived: 2, updateTime: 2021-07-14T02:33:29.000Z },
  { totalReceived: 2, updateTime: 2021-07-14T02:33:24.000Z },
  { totalReceived: 4, updateTime: 2021-07-14T02:33:24.000Z }`

it's include update time  >2021-7-1 0-0-0 in database.

may be this is a bug?

**Comment by kevinresol** [comment]
What is the generated sql? (Enable with `-D sql-debug`)

**Comment by sonygod** [comment]
new Date(2021,6,1,0,0,0)

```haxe
SELECT `F_NODE`.`totalReceived` AS `totalReceived`, `F_NODE`.`updateTime` AS `updateTime` FROM `fa_node` AS `F_NODE` WHERE ((`F_NODE`.`updateTime` >= DATE_ADD(FROM_UNIXTIME(0), INTERVAL 1625068800 SECOND)) AND (`F_NODE`.`totalReceived` > 1))
`

`
new Date(2021,7,1,0,0,0)`


```haxe
SELECT `F_NODE`.`totalReceived` AS `totalReceived`, `F_NODE`.`updateTime` AS `updateTime` FROM `fa_node` AS `F_NODE` WHERE ((`F_NODE`.`updateTime` >= DATE_ADD(FROM_UNIXTIME(0), INTERVAL 1627747200 SECOND)) AND (`F_NODE`.`totalReceived` > 1))`

**Comment by kevinresol** [comment]
Is the date produced by date_add not correct?

**Comment by sonygod** [comment]
it's seem  second not correct   **1627747200**

**Comment by sonygod** [comment]
[fa_node_copy1.zip](https://github.com/haxetink/tink_sql/files/6816685/fa_node_copy1.zip)

here is my sql data file

**Comment by sonygod** [comment]
@kevinresol 

**select DATE_ADD(FROM_UNIXTIME(0), INTERVAL 1627747200 SECOND)**

will got ,don't know why will auto add extra one month here?

**2021-08-01 00:00:00**

**Comment by sonygod** [comment]
look at this js native code ..and got the diff result.

```haxe
var d3 = new Date(2021,7,1,0,0,0)
console.log(d3.getTime()) //1627747200-000

const date2 = new Date('2021-07-01T00:00:00');
console.log(date2.getTime())//1625068800-000
```

**Comment by kevinresol** [comment]
Month in Date constructor is zero based
