### ISSUE TITLE
how to write select * ? in tink_sql?

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_sql#139]
how to write select * ? in tink_sql?

```haxe
@await db.F_NODE.select(*).where(F_NODE.updateTime >= thisMonth()).all();//   how to write select * here? 
```

**Comment by kevinresol** [comment]
You can just omit the select call

**Comment by kevinresol** [comment]
also please note that github issue list is not for questions. please ask questions in gitter or discord.
