### ISSUE TITLE
Carry data type in EConst

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#24]
by renaming it to `EValue(v:T, type:ValueType)`

and 

```haxe
enum ValueType {
  Primitive; // (bool, int, float, string)
  Bytes;
  Array(type:ValueType);
  Point; // (spacial data)
  // ... more to come
}
```

This helps the formatter to do its job.

**Comment by back2dos** [comment]
Sounds good ;)

**Comment by kevinresol** [comment]
Added here: https://github.com/haxetink/tink_sql/pull/23/commits/61e4ed1de4849fa44652ddc1351407e97832d456

**Comment by back2dos** [comment]
Seems like this is on master for a while now.
