### ISSUE TITLE
[SQL Server] Distinguish duplicated column names

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#25]
I am using the [`mssql`](https://github.com/patriksimek/node-mssql) npm lib which uses [`tedious`](https://github.com/tediousjs/tedious) driver (implementation of the TDS protocol)

Suppose we have two tables `tb1` and `tbl2` and both contains a column `name`;

`SELECT * from tbl1, tbl2` will result in `{name:['entry_from_tbl1', 'entry_from_tbl2']}` i.e. the values are pushed into an array.

Seems that the library or protocol doesn't support returning the name of the origin table of a column (I am not 100% sure, but let's assume it is so). I wonder if we should generate the SELECT statement such that the origin table could be distinguished.

**Comment by kevinresol** [comment]
Since [the TDS protocol doesn't support this](https://github.com/tediousjs/tedious/issues/591#issuecomment-316541785), we will probably need to use some aliasing to distinguish the columns.

**Comment by benmerckx** [comment]
Fields are now aliased when needed (#82)
