### ISSUE TITLE
Should use table's member name in query

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#26]
I have this entry in my db: `@:table('realName') var ident:MyModel;`

In a query I have to write: `db.ident.where(realName.id = 'val')`

I think it should be `ident.id` instead?

**Comment by back2dos** [comment]
Makes sense, yes. I think it's because it passes through the same aliasing logic ^^

**Comment by benmerckx** [comment]
Should be fixed with 3f30d14

**Comment by back2dos** [comment]
Ok, well, please reopen if it resurfaces ;)
