### ISSUE TITLE
OrderBy issues

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#30]
As mentioned in the PR, it is not type safe because the column name is specified as String.
Also, it fails with "ambiguous column" when trying to order a joined table where two tables have columns of the same name.

**Comment by back2dos** [comment]
Hmm, I wonder if for now you couldn't make the columns be specified per `Field`? That would disambiguiate and also make it slightly more type safe ... you could still pull in fields from tables not in the result set, but it's a start.

**Comment by kevinresol** [comment]
Oh I didn't know `Field` carries the table name. What would be the easiest way to reference / create a `Field`?

**Comment by back2dos** [comment]
Every dataset (and table in particular) has it's [fields](https://github.com/haxetink/tink_sql/blob/pure/src/tink/sql/Dataset.hx#L12), e.g.: `db.User.fields.name`.

Actually, something like this should work:

```haxe
typedef OrderBy = Array<{field:Field, order:Order}>;

public function stream(?limit:Limit, ?orderBy:Fields->Iterable<OrderBy>):RealStream<Result>
    return cnx.selectAll(target, condition, limit, orderBy(fields));

db.Table.stream(100...200, function (result) return [{ field: result.column2, order: Asc }])
someJoin.stream(100.200, function (result) return [{ field: result.table1.column1, order: Asc }])
```
