### ISSUE TITLE
Driver-specific options

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#38]
For things like these: https://github.com/haxetink/tink_sql/blob/5240624/src/tink/sql/drivers/node/MySql.hx#L31

**Comment by kevinresol** [comment]
@back2dos any insight on this?

**Comment by back2dos** [comment]
Hmm, how about instantiating the driver by hand and altering it slightly?

```haxe
class MySql implements Driver {
  // ...
  public function new(settings, ?connectionLimit = 3) {
    this.settings = settings;
    this.connectionLimit = connectionLimit;
  }
  // ...
}
```

(if this is something that comes up a lot, maybe you want to group the specific settings into an additional object).
