### ISSUE TITLE
Updating the schema

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_sql#43]
I'd like to add a way to diff and update the schema in tink_sql. Would that be appropriate or should I try and separate it as another library? I'm thinking of something like this:
```haxe
enum SchemaChange {
 Added(field, sqltype);
 Changed(field, oldtype, newtype);
 Removed(field);
}
// on Table:
diffSchema(): Promise<Array<SchemaChange>>
updateSchema(changes: Array<SchemaChange>): Promise<Noise>
```
So you can filter the changes and apply those needed.

**Comment by back2dos** [comment]
Feel free to put it here ;)
