### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_sql#46]
I had a try at adding aggregation last night, along these lines:
````haxe
db.Table.select(function (Table) return {id: Table.id})
// or implicit
db.Table.select({id: Table.id})
// which allows tink.sql.Expr, and further filtering
db.Table.select({bool: Table.id > 40}).where(Table.id > 20)
````
Having everything named makes it easier to parse the results afterwards and is in line with #13. Basically we keep the selection data in `Dataset` (in my test setup I put it in a new constructor in `Target`, but that's not the way to go). The `select` call runs a macro to determine how the `Result: {}` of `Dataset` must be changed and returns a new `Dataset` with a modified `selection`. Am I right in thinking the type param in `Expr<T>` would determine the type used in `Result`? 

The `selection` could be a `Map<String, Expr<Any>>` or a similar array or object. Once we get to the formatter it can read the `selection` and output which fields we're selecting. Calling `select` more than once could add to the fields being selected.

Does this seem like a good way to move forward?

**Comment by back2dos** [comment]
In principle, that looks like the right direction. The `Result` should have the type of the actual rows you're expecting and the `Fields` should have all the fields available in the where clause (which in this case means the original table columns *and* the result columns).

**Comment by benmerckx** [comment]
Not sure if we need to add the result columns to the fields. I think you can only access those if you're using `HAVING`, but not in a `WHERE` clause.

**Comment by back2dos** [comment]
Hmm, it seems you can: http://sqlfiddle.com/#!9/7e1ee9/180 - or is that maybe MySQL specific?

**Comment by benmerckx** [comment]
I'm not sure we're talking about the same thing :) The `rev` in your example is a column and thus can be used in where (which would already be in `Fields`) but you can't do this: 
````sql
SELECT rev as version, content FROM docs WHERE version > 1;
````
Which does work with having:
````sql
SELECT rev as version, content FROM docs HAVING version > 1;
````
This:
> (which in this case means the original table columns and the result columns)

Made me think you meant we'd include `version` too, or is where I misunderstood :)
Like this (which wouldn't work), but could be added later with a having method that includes the current selection aliases.
````haxe
db.docs({version: docs.rev, content: docs.content}).where(version > 1)
````

**Comment by back2dos** [comment]
Yeah, sorry, you're right. I first tried it on w3schools, where `SELECT CustomerID AS ID, CustomerName AS Customer
FROM Customers WHERE ID < 5;` seems to work: https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_alias_column0

Then I realized that it I should try it with a real database, but messed it up. So please disregard my comment ;)

**Comment by benmerckx** [comment]
I got this working here https://github.com/benmerckx/tink_sql/tree/aggregation :)
It builds on #45 so I'll wait for that to be accepted and add more tests before submitting a PR.
Two more questions:
- Should multiple selects be merged? And should it fail on selecting a duplicate field or overwrite it?
- Is T in Expr<T> always the resulting type?

**Comment by back2dos** [comment]
> Should multiple selects be merged? 

By "multiple", do you mean "chained"? One option would be to disallow that. Calling `select` on a `Dataset` could return a `Selection` (which would not have a `select` method). Or do you see any advantage in having multiple selects?

> And should it fail on selecting a duplicate field or overwrite it?

I guess it should fail.

> Is `T` in `Expr<T>` always the resulting type?

Indeed.

**Comment by benmerckx** [comment]
Maybe it's easiest to start with a subclass of `Dataset` (eg `Selectable`) which has the `select` method and return a plain `Dataset` after selection? As otherwise it would have to mirror all `Dataset` methods.

**Comment by back2dos** [comment]
Yeah, sure. It should be something along the lines of `Table extends Selectable extends Dataset` ;)
