### ISSUE TITLE
Record Macro vs Tink SQL

### ISSUE THREAD

**Issue by hoseyjoe** [haxetink/tink_sql#53]
Just curious for a  comparison.  Both run as Macros?  Tink SQL seems active, not sure about record Macros.  Either more stable?

**Comment by back2dos** [comment]
Record macros is an ORM, while tink_sql embeds SQL into Haxe - not unlike Linq (although far less complete).

As for stability, I think record macros is definitely more stable and if you need more features, consider [ufront-orm](https://github.com/ufront/ufront-orm) which extends it with more relationships. However neither run on nodejs. Right now, tink_sql works on Node and it seems on PHP too (maybe @benmerckx can comment on that). It's a bit of a PITA to set up though, and there are plans for a number of breaking changes. But if you're brave, don't hesitate to [join us on gitter](gitter.im/haxetink/public) ;)

**Comment by benmerckx** [comment]
Except for #52 (which I'll fix very soonish) and a few missing geojson types PHP is on par with the Node driver :)

**Comment by hoseyjoe** [comment]
Thank you
