### ISSUE TITLE
EXISTS and subqueries

### ISSUE THREAD

**Issue by sh-dave** [haxetink/tink_sql#55]
Is it already possible to do [EXISTS](https://www.w3schools.com/sql/sql_exists.asp) or subqueries at all?
If so, i'd appreciate a small example, b/c i couldn't figure out how 😅

**Comment by kevinresol** [comment]
They are not yet supported

**Comment by benmerckx** [comment]
Exists has been added to functions and basic subquery support was merged. Closing in favor of #63
