### ISSUE TITLE
Format and queries

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_sql#58]
While looking into extending tink_sql a bit more (subqueries, union etc) I think we could first cleanup `Format` a bit. Making it an instance which can be subclassed should help move out stuff specific to MySql (or other databases). It could be constructed with a `Sanitizer` so that doesn't have to be passed in each method. It could require an interface to be implemented, but alternatively I'd like to suggest an intermediate 'AST' of the SQL is passed. I think this would help construct queries by alternative means (in cases where you only have type information at runtime), and should become a useful data structure to contain subqueries. Something along these lines:

````haxe
package tink.sql;

import tink.sql.Connection;
import tink.sql.Expr;
import tink.sql.Info;
import tink.sql.Limit;
import tink.sql.Types;

enum Sql<Db, Result> {
  Union<Row: {}>(a: Sql<Db, Stream<Row>>, b: Sql<Db, Stream<Row>>, distinct: Bool): Sql<Db, Stream<Row>>;
  Select<Row: {}, Condition>(select: SelectOperation<Db, Row, Condition>): Sql<Db, Stream<Row>>;
  Insert<Row: {}>(insert: InsertOperation<Row>): Sql<Db, Promise<Id<Row>>>;
  Update<Row: {}, Condition>(update: UpdateOperation<Row, Condition>): Sql<Db, Promise<{rowsAffected: Int}>>;
  Delete<Row: {}, Condition>(delete: DeleteOperation<Row, Condition>): Sql<Db, Promise<{rowsAffected: Int}>>;
  CreateTable<Row: {}>(table: TableInfo<Row>): Sql<Db, Promise<Noise>>;
  DropTable<Row: {}>(table: TableInfo<Row>): Sql<Db, Promise<Noise>>;
  AlterTable<Row: {}>(table: TableInfo<Row>, change: AlterTableOperation): Sql<Db, Promise<Noise>>;
  ShowColumns<Row: {}, Info>(from: TableInfo<Row>): Sql<Db, Promise<Info>>;
  ShowIndex<Row: {}, Info>(from: TableInfo<Row>): Sql<Db, Promise<Info>>;
}

typedef SelectOperation<Db, Row: {}, Condition> = {
  from: Target<Row, Db>,
  ?selection: Selection<Row>,
  ?where: Condition,
  ?limit: Limit,
  ?orderBy: OrderBy<Row>,
  //?groupBy: GroupBy
}

typedef UpdateOperation<Row: {}, Condition> = {
  table:TableInfo<Row>,
  set: Update<Row>,
  ?where: Condition,
  ?max: Int
}

typedef DeleteOperation<Row: {}, Condition> = {
  table:TableInfo<Row>,
  ?where: Condition,
  ?max: Int
}

typedef InsertOperation<Row: {}> = {
  table:TableInfo<Row>,
  rows: Array<Insert<Row>>,
  ?ignore: Bool
}

typedef TableColumn = {
  name: String,
  type: String,
  autoIncrement: Bool,
  nullable: Bool,
  keys: Array<KeyType>,
  byDefault: Null<String>
}

typedef Index = {
  name: String,
  type: IndexType,
  fields: Array<String>
}

enum IndexType {
  IPrimary;
  IUnique;
  IIndex;
}

enum AlterTableOperation {
  AddColumn(col: TableColumn);
  AddIndex(index: Index);
  AlterColumn(to: TableColumn, ?from: TableColumn);
  DropColumn(col: TableColumn);
  DropIndex(index: Index);
}
````

**Comment by back2dos** [comment]
Yeah, looks good, although it's probably quite a bit of work.

After that, I guess you could then do:

```haxe
interface Connection<Db> {
  function execute<Result>(query:Sql<Db, Result>):Result;
}
```

In that case I guess you'd want to tweak the result types in `Sql` a little (using `Stream` and `Promise` respectively).

As for `Query`, I'm not sure it's worth adding, as I can't think of "useful stuff" to put in there. But I'm curious to see what you can think of ;)

**Comment by benmerckx** [comment]
> In that case I guess you'd want to tweak the result types in Sql a little (using Stream and Promise respectively).

That sounds pretty useful, I've updated the example code.

> As for Query, I'm not sure it's worth adding, as I can't think of "useful stuff" to put in there. But I'm curious to see what you can think of ;)

I must admit of not thinking that far ahead :) My only thought now is a toString method (to get a quick look at the sql generated) but it would need a formatter to do so anyway. I've removed it for now.
