### ISSUE TITLE
Insert should (?) return multiple ids

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_sql#81]
Since we can pass multiple rows:
`Query<Db, Promise<Id<Row>>>` => `Query<Db, Promise<Array<Id<Row>>>>`

**Comment by benmerckx** [comment]
Also, inserting multiple rows generates invalid sql currently.

**Comment by kevinresol** [comment]
iirc mysql only returns the last inserted id

**Comment by benmerckx** [comment]
True, there's some work arounds but they'll be different for each database engine anyway. Don't think we can reliably support this or if it's worth putting in the work, so I'll close this for now.
