### ISSUE TITLE
Limit fromIter

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#88]
https://github.com/haxetink/tink_sql/blob/b57a659edc0cf93cfce5358922a12fef3dc84b09/src/tink/sql/Limit.hx#L12

Should this be `{limit: i.max - i.min, offset:i.min}`?

So `100...110` would give `{limit: 10, offset: 100}`

**Comment by benmerckx** [comment]
Duplicate of #85 I think. I agree, I'd expect it to work more like a from ... to

**Comment by kevinresol** [comment]
Alright
