### ISSUE TITLE
Crash when table name is aliased

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_sql#98]
```haxe
db.foo.join(db.foo.as('bar')).on(foo.id == bar.id)...
```

crashes here:

https://github.com/haxetink/tink_sql/blob/404c3cb100cf7737e6f257eacb2b7d949c7bbaa1/src/tink/sql/expr/ExprTyper.hx#L84

Because `bar` is not found in the `tables` map

**Comment by benmerckx** [comment]
I wonder if we should just store the type in `EField` like in `EValue` (and `ECall` recently)

https://github.com/haxetink/tink_sql/blob/c1588352490d03782c68bec0c364a2dd571d6498/src/tink/sql/Expr.hx#L16-L17

**Comment by benmerckx** [comment]
Sorry, mentioned wrong issue in the commit

**Comment by benmerckx** [comment]
Was actually fixed in #102 but forgot to close
